/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: battery.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "battery.pb-c.h"
void   battery__stat__init
                     (Battery__Stat         *message)
{
  static const Battery__Stat init_value = BATTERY__STAT__INIT;
  *message = init_value;
}
size_t battery__stat__get_packed_size
                     (const Battery__Stat *message)
{
  assert(message->base.descriptor == &battery__stat__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t battery__stat__pack
                     (const Battery__Stat *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &battery__stat__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t battery__stat__pack_to_buffer
                     (const Battery__Stat *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &battery__stat__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Battery__Stat *
       battery__stat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Battery__Stat *)
     protobuf_c_message_unpack (&battery__stat__descriptor,
                                allocator, len, data);
}
void   battery__stat__free_unpacked
                     (Battery__Stat *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &battery__stat__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor battery__stat__field_descriptors[18] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, load),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_temperature",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, battery_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relay",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, relay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "off_reason",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, off_reason),
    &battery__off_reason__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yield_total",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, yield_total),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yield_today",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, yield_today),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_power_today",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, max_power_today),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yield_yesterday",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, yield_yesterday),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_power_yesterday",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, max_power_yesterday),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, error),
    &battery__error__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, state),
    &battery__state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware_version",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, firmware_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "product_id",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, product_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, serial_number),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "day_number",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, day_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Battery__Stat, mode),
    &battery__mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned battery__stat__field_indices_by_name[] = {
  3,   /* field[3] = battery_temperature */
  1,   /* field[1] = current */
  16,   /* field[16] = day_number */
  11,   /* field[11] = error */
  13,   /* field[13] = firmware_version */
  2,   /* field[2] = load */
  8,   /* field[8] = max_power_today */
  10,   /* field[10] = max_power_yesterday */
  17,   /* field[17] = mode */
  5,   /* field[5] = off_reason */
  14,   /* field[14] = product_id */
  4,   /* field[4] = relay */
  15,   /* field[15] = serial_number */
  12,   /* field[12] = state */
  0,   /* field[0] = timestamp */
  7,   /* field[7] = yield_today */
  6,   /* field[6] = yield_total */
  9,   /* field[9] = yield_yesterday */
};
static const ProtobufCIntRange battery__stat__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 18 }
};
const ProtobufCMessageDescriptor battery__stat__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "battery.Stat",
  "Stat",
  "Battery__Stat",
  "battery",
  sizeof(Battery__Stat),
  18,
  battery__stat__field_descriptors,
  battery__stat__field_indices_by_name,
  1,  battery__stat__number_ranges,
  (ProtobufCMessageInit) battery__stat__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue battery__off_reason__enum_values_by_number[10] =
{
  { "OFF_PLACEHOLDER", "BATTERY__OFF_REASON__OFF_PLACEHOLDER", 0 },
  { "OFF_NO_POWER", "BATTERY__OFF_REASON__OFF_NO_POWER", 1 },
  { "OFF_SWITCHED_OFF_POWER", "BATTERY__OFF_REASON__OFF_SWITCHED_OFF_POWER", 2 },
  { "OFF_SWITCHED_OFF_REGISTER", "BATTERY__OFF_REASON__OFF_SWITCHED_OFF_REGISTER", 4 },
  { "OFF_REMOTE_INPUT", "BATTERY__OFF_REASON__OFF_REMOTE_INPUT", 8 },
  { "OFF_PROTECTION", "BATTERY__OFF_REASON__OFF_PROTECTION", 16 },
  { "OFF_PAYGO", "BATTERY__OFF_REASON__OFF_PAYGO", 32 },
  { "OFF_BMS", "BATTERY__OFF_REASON__OFF_BMS", 64 },
  { "OFF_ENGINE_SHUTDOWN", "BATTERY__OFF_REASON__OFF_ENGINE_SHUTDOWN", 128 },
  { "OFF_ANALYSING_INPUT", "BATTERY__OFF_REASON__OFF_ANALYSING_INPUT", 256 },
};
static const ProtobufCIntRange battery__off_reason__value_ranges[] = {
{0, 0},{4, 3},{8, 4},{16, 5},{32, 6},{64, 7},{128, 8},{256, 9},{0, 10}
};
static const ProtobufCEnumValueIndex battery__off_reason__enum_values_by_name[10] =
{
  { "OFF_ANALYSING_INPUT", 9 },
  { "OFF_BMS", 7 },
  { "OFF_ENGINE_SHUTDOWN", 8 },
  { "OFF_NO_POWER", 1 },
  { "OFF_PAYGO", 6 },
  { "OFF_PLACEHOLDER", 0 },
  { "OFF_PROTECTION", 5 },
  { "OFF_REMOTE_INPUT", 4 },
  { "OFF_SWITCHED_OFF_POWER", 2 },
  { "OFF_SWITCHED_OFF_REGISTER", 3 },
};
const ProtobufCEnumDescriptor battery__off_reason__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "battery.OffReason",
  "OffReason",
  "Battery__OffReason",
  "battery",
  10,
  battery__off_reason__enum_values_by_number,
  10,
  battery__off_reason__enum_values_by_name,
  8,
  battery__off_reason__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue battery__error__enum_values_by_number[20] =
{
  { "ERROR_NONE", "BATTERY__ERROR__ERROR_NONE", 0 },
  { "ERROR_BATTERY_VOLTAGE_HIGH", "BATTERY__ERROR__ERROR_BATTERY_VOLTAGE_HIGH", 2 },
  { "ERROR_CHARGER_TEMP_HIGH", "BATTERY__ERROR__ERROR_CHARGER_TEMP_HIGH", 17 },
  { "ERROR_CHARGER_CURRENT_HIGH", "BATTERY__ERROR__ERROR_CHARGER_CURRENT_HIGH", 18 },
  { "ERROR_CHARGER_CURRENT_REVERSED", "BATTERY__ERROR__ERROR_CHARGER_CURRENT_REVERSED", 19 },
  { "ERROR_BULK_TIME_LIMIT_EXCEEDED", "BATTERY__ERROR__ERROR_BULK_TIME_LIMIT_EXCEEDED", 20 },
  { "ERROR_CURRENT_SENSOR_ISSUE", "BATTERY__ERROR__ERROR_CURRENT_SENSOR_ISSUE", 21 },
  { "ERROR_TERMINALS_OVERHEATED", "BATTERY__ERROR__ERROR_TERMINALS_OVERHEATED", 26 },
  { "ERROR_CONVERTER_ISSUE", "BATTERY__ERROR__ERROR_CONVERTER_ISSUE", 28 },
  { "ERROR_SOLAR_VOLTAGE_HIGH", "BATTERY__ERROR__ERROR_SOLAR_VOLTAGE_HIGH", 33 },
  { "ERROR_SOLAR_CURRENT_HIGH", "BATTERY__ERROR__ERROR_SOLAR_CURRENT_HIGH", 34 },
  { "ERROR_SHUTDOWN_BATTERY_VOLTAGE", "BATTERY__ERROR__ERROR_SHUTDOWN_BATTERY_VOLTAGE", 38 },
  { "ERROR_SHUTDOWN_CURRENT_FLOW", "BATTERY__ERROR__ERROR_SHUTDOWN_CURRENT_FLOW", 39 },
  { "ERROR_LOST_COMMUNICATION", "BATTERY__ERROR__ERROR_LOST_COMMUNICATION", 65 },
  { "ERROR_SYNC_CONFIGURATION", "BATTERY__ERROR__ERROR_SYNC_CONFIGURATION", 66 },
  { "ERROR_BMS_CONNECTION", "BATTERY__ERROR__ERROR_BMS_CONNECTION", 67 },
  { "ERROR_NETWORK_CONFIG", "BATTERY__ERROR__ERROR_NETWORK_CONFIG", 68 },
  { "ERROR_FACTORY_CALIBRATION", "BATTERY__ERROR__ERROR_FACTORY_CALIBRATION", 116 },
  { "ERROR_BAD_FIRMWARE", "BATTERY__ERROR__ERROR_BAD_FIRMWARE", 117 },
  { "ERROR_SETTINGS_INVALID", "BATTERY__ERROR__ERROR_SETTINGS_INVALID", 119 },
};
static const ProtobufCIntRange battery__error__value_ranges[] = {
{0, 0},{2, 1},{17, 2},{26, 7},{28, 8},{33, 9},{38, 11},{65, 13},{116, 17},{119, 19},{0, 20}
};
static const ProtobufCEnumValueIndex battery__error__enum_values_by_name[20] =
{
  { "ERROR_BAD_FIRMWARE", 18 },
  { "ERROR_BATTERY_VOLTAGE_HIGH", 1 },
  { "ERROR_BMS_CONNECTION", 15 },
  { "ERROR_BULK_TIME_LIMIT_EXCEEDED", 5 },
  { "ERROR_CHARGER_CURRENT_HIGH", 3 },
  { "ERROR_CHARGER_CURRENT_REVERSED", 4 },
  { "ERROR_CHARGER_TEMP_HIGH", 2 },
  { "ERROR_CONVERTER_ISSUE", 8 },
  { "ERROR_CURRENT_SENSOR_ISSUE", 6 },
  { "ERROR_FACTORY_CALIBRATION", 17 },
  { "ERROR_LOST_COMMUNICATION", 13 },
  { "ERROR_NETWORK_CONFIG", 16 },
  { "ERROR_NONE", 0 },
  { "ERROR_SETTINGS_INVALID", 19 },
  { "ERROR_SHUTDOWN_BATTERY_VOLTAGE", 11 },
  { "ERROR_SHUTDOWN_CURRENT_FLOW", 12 },
  { "ERROR_SOLAR_CURRENT_HIGH", 10 },
  { "ERROR_SOLAR_VOLTAGE_HIGH", 9 },
  { "ERROR_SYNC_CONFIGURATION", 14 },
  { "ERROR_TERMINALS_OVERHEATED", 7 },
};
const ProtobufCEnumDescriptor battery__error__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "battery.Error",
  "Error",
  "Battery__Error",
  "battery",
  20,
  battery__error__enum_values_by_number,
  20,
  battery__error__enum_values_by_name,
  10,
  battery__error__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue battery__state__enum_values_by_number[9] =
{
  { "STATE_OFF", "BATTERY__STATE__STATE_OFF", 0 },
  { "STATE_FAULT", "BATTERY__STATE__STATE_FAULT", 2 },
  { "STATE_BULK", "BATTERY__STATE__STATE_BULK", 3 },
  { "STATE_ABSORPTION", "BATTERY__STATE__STATE_ABSORPTION", 4 },
  { "STATE_FLOAT", "BATTERY__STATE__STATE_FLOAT", 5 },
  { "STATE_EQUALIZE_MANUAL", "BATTERY__STATE__STATE_EQUALIZE_MANUAL", 7 },
  { "STATE_STARTING_UP", "BATTERY__STATE__STATE_STARTING_UP", 245 },
  { "STATE_EQUALIZE_AUTO", "BATTERY__STATE__STATE_EQUALIZE_AUTO", 247 },
  { "STATE_EXTERNAL_CONTROL", "BATTERY__STATE__STATE_EXTERNAL_CONTROL", 252 },
};
static const ProtobufCIntRange battery__state__value_ranges[] = {
{0, 0},{2, 1},{7, 5},{245, 6},{247, 7},{252, 8},{0, 9}
};
static const ProtobufCEnumValueIndex battery__state__enum_values_by_name[9] =
{
  { "STATE_ABSORPTION", 3 },
  { "STATE_BULK", 2 },
  { "STATE_EQUALIZE_AUTO", 7 },
  { "STATE_EQUALIZE_MANUAL", 5 },
  { "STATE_EXTERNAL_CONTROL", 8 },
  { "STATE_FAULT", 1 },
  { "STATE_FLOAT", 4 },
  { "STATE_OFF", 0 },
  { "STATE_STARTING_UP", 6 },
};
const ProtobufCEnumDescriptor battery__state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "battery.State",
  "State",
  "Battery__State",
  "battery",
  9,
  battery__state__enum_values_by_number,
  9,
  battery__state__enum_values_by_name,
  6,
  battery__state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue battery__mode__enum_values_by_number[3] =
{
  { "MODE_OFF", "BATTERY__MODE__MODE_OFF", 0 },
  { "MODE_LIMITED", "BATTERY__MODE__MODE_LIMITED", 1 },
  { "MODE_ACTIVE", "BATTERY__MODE__MODE_ACTIVE", 2 },
};
static const ProtobufCIntRange battery__mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex battery__mode__enum_values_by_name[3] =
{
  { "MODE_ACTIVE", 2 },
  { "MODE_LIMITED", 1 },
  { "MODE_OFF", 0 },
};
const ProtobufCEnumDescriptor battery__mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "battery.Mode",
  "Mode",
  "Battery__Mode",
  "battery",
  3,
  battery__mode__enum_values_by_number,
  3,
  battery__mode__enum_values_by_name,
  1,
  battery__mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
